# Generated by Django 3.2 on 2021-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youni_record', '0002_alter_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_zh',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_zh',
            field=models.CharField(max_length=100),
        ),
    ]
